### ISSUE TITLE
Metadata/license on PyPi

### ISSUE THREAD

**Issue by psobolewskiPhD** [vincefn/pyvkfft#14]
I noticed the GitHub says MIT (there's even a PR setting this), but on PyPi it's MPL.
I think this is a question of setup.py, but I'm not an expert in this sort of stuff.
I think
https://github.com/vincefn/pyvkfft/blob/b7b4c2cff1dddc81e1d904861d54c996153aa6f7/setup.py#L270
needs to be changed to show "MIT License".

Additionally, `pip show pyvkfft` doesn't show the license:
```
╰─ pip show pyvkfft                                               (napari-CL) ─╯
Name: pyvkfft
Version: 2022.1.1
Summary: Python wrapper for the CUDA and OpenCL backends of VkFFT,providing GPU FFT for PyCUDA, PyOpenCL and CuPy
Home-page: https://github.com/vincefn/pyvkfft
Author: Vincent Favre-Nicolin
Author-email: favre@esrf.fr
License: UNKNOWN
Location: /Users/piotrsobolewski/Dev/miniforge3/envs/napari-CL/lib/python3.9/site-packages
Requires: numpy, psutil, pyopencl
Required-by: 
```
So I think that metadata block needs a `license = MIT License`

**Comment by vincefn** [comment]
Thanks @psobolewskiPhD for pointing this out. The license was changed to follow VkFFT license, but I forgot to update the metadata. It's now corrected.
