### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ZJG0** [vincefn/pyvkfft#2]
The error is "The prime numbers of the FFT size is larger than 13". how to solve

**Comment by vincefn** [comment]
Look at the prime factors decomposition of the FFT dimensions and make sure that the only factors are 2,3,5,7,11 or 13.

For example use the `primes` function in either cuda or opencl:
``` python
from pyvkfft.cuda import primes
print(primes(57))  # -> [1, 3, 19], not OK
print(primes(56))  # -> [1, 2, 2, 2, 7], OK
```

**Comment by ZJG0** [comment]
I do not get the solution. The error appear when i run `app = VkFFTApp(x_c.shape, x_c.dtype, ndim=1)`, i need to edit the `x_c.shape` ?

**Comment by vincefn** [comment]
Yes the shape is the problem. What are the dimensions used ?

**Comment by ZJG0** [comment]
I want to calculate convolution by FFT，so the dimension is 1.
what should i do to calculate it ？

**Comment by vincefn** [comment]
I was talking about the size of the array, what is its shape ?

**Comment by ZJG0** [comment]
The shape is 65537

**Comment by vincefn** [comment]
primes(65537) = [1, 65537] so 65537 is a prime number... So cut you data to 65536 and you'll be fine.
